name: xp2p_sdk
description: Flutter SDK for Tencent IoT XP2P video streaming. This SDK provides P2P connectivity for video devices using Dart FFI.
version: 2.4.1
homepage: https://github.com/tencentyun/iot-link-android

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  path: ^1.8.3
  http: ^1.1.0
  crypto: ^3.0.3
  convert: ^3.1.1
#  tencent_rtc_sdk: ^12.8.2
  live_flutter_plugin: ^12.6.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.tencent.xp2p_sdk
        pluginClass: Xp2pSdkPlugin
      ios:
        pluginClass: Xp2pSdkPlugin
